---
title: "Analyses"
author: "Ran Ji"
date: "6/05/2017"
output: html_document
---

## Loading BetyDB into environment and joining to make main table
```{r db-connection}
library(dplyr)

bety_src <- src_postgres(dbname = "bety", 
                password = 'bety', 
                host = 'terra-bety.default', 
                user = 'bety', 
                port = 5432)

# to see all available columns in traits table
original_traits <- tbl(bety_src, 'traits') %>%
  collect(n=1)

# local version of variables for reference
variables_local <- tbl(bety_src, 'variables', n = Inf) %>%
  mutate(variable_id = id, variable_name = name) %>%
  dplyr::select(variable_id, variable_name, description, units) %>%
  collect()

traits <- tbl(bety_src, 'traits', n = Inf) %>%
  mutate(trait_id = id) %>%
  dplyr::select(trait_id, site_id, specie_id, cultivar_id, date, mean, variable_id, method_id, treatment_id, entity_id)

variables <- tbl(bety_src, 'variables', n = Inf) %>%
  mutate(variable_id = id, variable_name = name) %>%
  dplyr::select(variable_id, variable_name)

cultivars <- tbl(bety_src, 'cultivars', n = Inf) %>%
  mutate(cultivar_id = id, cultivar = name) %>%
  dplyr::select(cultivar_id, cultivar)

entities <- tbl(bety_src, 'entities', n = Inf) %>%
  mutate(entity_name = name, entity_id = id) %>%
  dplyr::select(entity_name, entity_id)

sites <- tbl(bety_src, 'sites', n = Inf) %>%
  mutate(site_id = id) %>%
  dplyr::select(site_id, city, state, country, notes, sitename)

treatments <- tbl(bety_src, 'treatments', n = Inf) %>%
  mutate(treatment_id = id, treatment_definition = definition, treatment_name = name) %>%
  dplyr::select(treatment_id, treatment_name, treatment_definition) 

# looking for when each season began
experiments <- tbl(bety_src, 'experiments', n = Inf) %>%
  #mutate(treatment_id = id, treatment_definition = definition, treatment_name = name) %>%
  #dplyr::select(treatment_id, treatment_name, treatment_definition) 
  collect(n = Inf)

# join relevant tables together
joined_table <- traits %>%
  left_join(variables, by = 'variable_id') %>%
  left_join(cultivars, by = 'cultivar_id') %>%
  left_join(entities, by = 'entity_id') %>%
  left_join(sites, by = 'site_id') %>%
  left_join(treatments, by = 'treatment_id') %>%
  dplyr::select(trait_id, date, mean, variable_name, sitename, treatment_name, entity_name, cultivar)
```

## Cleaning Up Table
```{r variable-tables}
library(lubridate)

# filter table for measurements that we care about
filtered_table <- filter(joined_table, variable_name %in% c("canopy_height", "plant_height")) %>%
  collect(n = Inf)

# filter table for rows without date
filtered_table <- filtered_table[is.na(filtered_table$date)]

# define variable indoor_outdoor based on sitename
filtered_table$indoor_outdoor <- ifelse(filtered_table$sitename == 'Danforth Plant Science Center Bellweather Phenotyping Facility', 'Indoor', 'Outdoor')

# define new variable Date that is a date type
filtered_table$Date <- as.Date(substr(filtered_table$date, 0, 10), format = "%Y-%m-%d")

# define new variable season based on which season the data was taken
filtered_table$season <- if_else(filtered_table$Date %within% interval(as.POSIXct("2014-01-01"), as.POSIXct("2014-12-31")), "Summer 2014", if_else(filtered_table$Date %within% interval(as.POSIXct("2016-01-01"), as.POSIXct("2016-08-01")), "Summer 2016", if_else(filtered_table$Date %within% interval(as.POSIXct("2016-08-15"), as.POSIXct("2016-12-31")), "Fall 2016", "N/A")))

# define new variable age based on when the season began
filtered_table$age <- if_else( , , ifelse(, , ))

# look at which sites have which variables and cultivars
site_variable <- filtered_table %>%
  group_by(indoor_outdoor, variable_name, cultivar) %>%
  summarize(n = n()) %>%
  collect(n = Inf)

outdoor_cultivar <- filter(site_variable, cultivar %in% c('BTx642', 'PI_564163', 'Tx430', 'TX7000')) %>%
  collect(n = Inf)

```

## Plotting
```{r plotting-height-vs-date}
library(ggplot2)
library(gridExtra)

# plotting the three types of heights against Date

# indoor variables

indoor_plant_height <- filter(filtered_table, variable_name == 'plant_height')

indoor_perimeter <- filter(filtered_table, variable_name == 'perimeter')

ggplot(indoor_plant_height, aes(x = Date, y = mean)) +
  geom_point(aes(color = cultivar)) +
  facet_wrap(~cultivar)
  ylab("Plant Height (Indoor)")

ggplot(indoor_plant_height, aes(x = Date, y = mean)) +
  geom_point(aes(color = treatment_name)) +
  ylab("Plant Height (Indoor)")

ggplot(indoor_perimeter, aes(x = Date, y = mean)) +
  geom_point(aes(color = treatment_name)) +
  ylab("Perimeter (Indoor)")

# outdoor variables

outdoor_canopy_height <- filter(filtered_table, variable_name == 'canopy_height')

ggplot(outdoor_canopy_height, aes(x = Date, y = mean)) +
  geom_point() +
  ylab("Canopy Height (Outdoor)")

ggplot(outdoor_canopy_height, aes(x = Date, y = mean)) +
  geom_point() +
  ylab("Canopy Height (Outdoor)")

ggplot(outdoor_canopy_height, aes(x = Date, y = mean)) +
  geom_point(aes(size = 0.1)) +
  ylab("Canopy Cover (Outdoor)")

# outdoor and Indoor - Shared Cultivars
indoor_cultivar <- ggplot(indoor_plant_height, aes(x = Date, y = mean)) +
  geom_point(aes(color = cultivar)) +
  facet_wrap(~cultivar) +
  ylab("Plant Height (Indoor)")

outdoor_cultivar <- ggplot(filter(outdoor_canopy_height, cultivar %in% c('BTx642', 'PI_564163', 'Tx430', 'TX7000')), aes(x = Date, y = mean)) +
  geom_point(aes(color = cultivar)) +
  facet_wrap(~cultivar) +
  ylab("Canopy Height (Outdoor)")

grid.arrange(indoor_cultivar, outdoor_cultivar)

```
## Converting date into estimated age for each data point

```{r}


```


## Modeling Growth Rates

```{r}
#need to install package 'growthrates' first
h0 <- lm(mean ~ Date, data = indoor_plant_height)



```